name = "make_lineage"
version = "0.1.0"
defaultTargets = ["ml"]
testDriver = "tests"

[[lean_lib]]
name = "Graph"
srcDir = "src"

[[lean_lib]]
name = "Command"
srcDir = "src"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "main"

[[lean_exe]]
name = "ml"
srcDir = "src"
root = "Main"

[[lean_lib]]
name = "Tests"
srcDir = "tests"
globs = ["Tests.+"]

[[lean_exe]]
name = "tests"
srcDir = "tests"
root = "Test"
